variables:
  pool: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: build   # Name of the pipeline resource
    source: MyBeerCellar.API - Build # Name of the pipeline referenced by the pipeline resource
    # trigger: 
    #   branches:
    #   - master

stages:
- stage: ReleaseDev
  displayName: 'Release Dev'
  jobs:
    - job: Release
      displayName: 'Release'
      pool:
        vmImage: $(pool)
      steps:
        - task: Bash@3
          displayName: 'Test'
          inputs:
             targetType: inline
             script: 'ls -al .'