resources:
  pipelines:
  - pipeline: build   # Name of the pipeline resource
    source: 'MyBeerCellar.API - Build' # Name of the pipeline referenced by the pipeline resource

variables:
  skipComponentGovernanceDetection: true
  pool: 'ubuntu-latest'
  azure-sub-dev: 'AIRS'
  azure-sub-prod: 'MSDN'
  location: 'eastus'
  infrastructure-arm-template: '$(Pipeline.Workspace)/build/Infrastructure/mybeercellar-api.json'

stages:
 - stage: Development
   displayName: 'Dev Release Stage'
   variables:
     resource-group: 'mybeercellar'
   jobs:
   - deployment: 'Deploy'
     environment: 'Development'
     pool:
       vmImage: $(pool)
     strategy:
      runOnce:
        deploy:
         steps:
           - task: Bash@3
             displayName: 'Test1111'
             inputs:
               targetType: inline
               script: ls -al $(Pipeline.Workspace)/build/Infrastructure
           - task: AzureResourceGroupDeployment@2
             displayName: 'Deploy Infrastructure'
             inputs:
                azureSubscription: $(azure-sub-dev)
                csmFile: $(infrastructure-arm-template)
                resourceGroupName: $(resource-group)
                location: $(location)
 - stage: Production
   displayName: 'Production Release Stage'
   variables:
     resource-group: 'my-beer-cellar-prod'
   jobs:
   - deployment: 'Deploy'
     environment: 'Production'
     pool:
       vmImage: $(pool)
     strategy:
      runOnce:
        deploy:
          steps:
           - task: AzureResourceGroupDeployment@2
             displayName: 'Deploy Infrastructure'
             inputs:
               azureSubscription: $(azure-sub-prod)
               csmFile: $(infrastructure-arm-template)
               resourceGroupName: $(resource-group)
               location: $(location)
